# see more config
# http://rqalpha.readthedocs.io/zh_CN/stable/intro/run_algorithm.html
version: 0.1.6

# 白名单，设置可以直接在策略代码中指定哪些模块的配置项目
whitelist: [base, extra, validator, mod]

base:
  # 数据源所存储的文件路径
  data_bundle_path: E:\evilAlpha\bundle
  # 回测起始日期
  start_date: 2018-01-01
  # 回测结束日期(如果是实盘，则忽略该配置)
  end_date: 2018-05-07
  # 目前支持 `1d` (日线回测) 和 `1m` (分钟线回测)，如果要进行分钟线，请注意是否拥有对应的数据源，目前开源版本是不提供对应的数据源的。
  frequency: 1d
  # Benchmark，如果不设置，默认没有基准参照。
  benchmark: 000300.XSHG
  # 在模拟交易和实盘交易中，RQAlpha支持策略的pause && resume，该选项表示开启 resume 功能
  resume_mode: false
  # 在模拟交易和实盘交易中，RQAlpha支持策略的pause && resume，该选项表示开启 persist 功能呢，
  # 其会在每个bar结束对进行策略的持仓、账户信息，用户的代码上线文等内容进行持久化
  persist: false
  persist_mode: real_time
  # 设置策略可交易品种，目前支持 `stock` (股票账户)、`future` (期货账户)，您也可以自行扩展
  accounts:
    # 如果想设置使用某个账户，只需要增加对应的初始资金即可
    stock: 1000000
    future: ~
  # 设置初始仓位
  init_positions: {}
  sourcePath: E:\evilAlpha\staralpha\ipynbs
  adminDB: {"host":"172.18.44.231","port": 3306,"db": "Test","user": "test","passwd": "test"}
  monitorMail:
    {"host":"smtp.exmail.qq.com","uname":"receiver.quant@591hx.com","passwd":"mn@Rx12","group":["chunlin.xu@591hx.com"]}

mod:
  sys_analyser:
    enabled: false
  sys_simulation:
    enabled: false
  sys_accounts:
    enabled: true
  alphaStar_utils:
    enabled: true
  alphaStar_tgw:
    enabled: true
    # 淘股王调仓借口url
    tgwurl: "http://www.tgw360.com/tgwapi/myapp/Trade/"
    #"http://www.tgw360.com/tgwapi/myapp/Trade/"
    #"http://www.tgwtest.com/tgwapi/myapp/Trade"
    secretId: "commonkey"
    #"commonkey"
    secretKey: "TGW_COMMONKEY"
    #"TGW_COMMONKEY"
    #淘股王实时行情接口url
    tickurl: "http://tgw360.com/webapi/myapp/WxInterface/GetQueInfo"
    #"http://tgw360.com/webapi/myapp/WxInterface/GetQueInfo"
    secretId_TICK: "dianziqianzhang"
    #"dianziqianzhang"
    secretKey_TICK: "B123456789"
    #"B123456789"

    # 账户信息
    uid: 63790
    combid: ~
    accountid: ~
    starting_cash: 10000000
#  alphaStar_mgr:
#    enabled: true
  alphaStar_factors:
    enabled: true
    factor_data_path: E:\evilAlpha\test
    factor_data_init_date: 2018-01-01
    extra:
      jydb: {"host":"172.18.44.5","port": 3306,"db": "jydb","user": "liangh","passwd": "huaxun!@#db"}

extra:
  # 选择日期的输出等级，有 `verbose` | `info` | `warning` | `error` 等选项，您可以通过设置 `verbose` 来查看最详细的日志，
  # 或者设置 `error` 只查看错误级别的日志输出
  log_level: info
  user_system_log_disabled: false
  user_log_disabled: false
  # 通过该参数可以将预定义变量传入 `context` 内。
  context_vars: ~
  # force_run_init_when_pt_resume: 在PT的resume模式时，是否强制执行用户init。主要用于用户改代码。
  force_run_init_when_pt_resume: false
  # enable_profiler: 是否启动性能分析
  enable_profiler: false
  # 选择是否开启分红再投资
  dividend_reinvestment: false
  is_hold: false
  locale: zh_Hans_CN
  logger: []

validator:
  # cash_return_by_stock_delisted: 开启该项，当持仓股票退市时，按照退市价格返还现金
  cash_return_by_stock_delisted: false
  # close_amount: 在执行order_value操作时，进行实际下单数量的校验和scale，默认开启
  close_amount: true
